version: "3"
services:
  myretail:
    image: com.example/myretail-rest-api:latest
    network_mode: default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure
    env_file:
      - env.list
    ports:
      - 8080:8080
    depends_on:
      - test-cass
    links:
      - test-cass
    stdin_open: true
    tty: true

  test-cass:
    image: cassandra:3.0.15
    network_mode: default
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
