version: "3"
services:
  myretail:
    image: com.myretail/myretail-rest-api:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
      restart_policy:
        condition: on-failure
    env_file:
      - env.list
    ports:
      - 8080:8080
    external_links:
      - local-cass:test-cass
    stdin_open: true
    tty: true
